<?php

/**
 * Implements hook_menu().
 */
function classy_menu() {
  $items['examples/classy'] = array(
    'page callback' => 'classy_page',
    'access arguments' => array('access content'),
    'title' => 'Classy',
  );

  $items['admin/classy'] = array(
    'title' => 'ClassySIS',
    'description' => 'Administer the Class Registration System.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );

  $items['admin/classy/students'] = array(  // view
    'title' => 'Students',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('classy_student_settings_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'includes/classy_ui.admin.inc',
    'weight' => -20,
  );
  $items['admin/classy/instructors'] = array(  // view
    'title' => 'Instructors',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'classy_admin_instructors',
    'access arguments' => array('access administration pages'),
    'weight' => -10,
  );  
  $items['admin/classy/instructors'] = array(  // view
    'title' => 'Instructors',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'classy_admin_instructors',
    'access arguments' => array('access administration pages'),
    'weight' => -10,
  ); 
  $items['admin/classy/config'] = array(
    'title' => 'Classy Configuration',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 50,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );
  
  
  
  return $items;
}

/**
 * Custom callback that builds our content and returns it to the browser. @todo replace with view
 *
 * @return
 *   a build array
 *
 */
function classy_page() {
  $build = array();
  $sql = 'SELECT nid FROM {node} n WHERE n.type = :type AND n.status = :status';
  $result = db_query($sql,
    array(
      ':type' => 'class',
      ':status' => 1,
    )
  );

  // Loop through each of our classy nodes and instruct node_view
  // to use our custom "example_node_list" view.
  // http://api.drupal.org/api/function/node_load/7
  // http://api.drupal.org/api/function/node_view/7
  foreach ($result as $row) {
    $node = node_load($row->nid);
    $build['node_list'][]= node_view($node, 'classy_list');
  }

  return $build;
}

function classy_admin_instructors() {
  return 'This will be the instructors area';
}

/**
 * Implements hook_entity_info_alter().
 *
 * We need to modify the default node entity info by adding a new view mode to
 * be used in functions like node_view() or node_build_content().
 *
 */
function classy_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['classy_list'] = array(
    'label' => t('Classy Node List'),
    'custom settings' => TRUE,
  );
}


/**
 * Implements hook_field_formatter_info().
 */
function classy_field_formatter_info() {
  return array(
    'classy_courses' => array(
      'label' => t('Classy Course Handle'),
      'field types' => array('text'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * @todo: We need to provide a formatter for the colors that a user is allowed to enter
 * during node creation.
 */
/*function classy_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'classy_colors':
      foreach ($items as $delta => $item) {
        $element[$delta]['#type'] = 'markup';
        $color = $item['safe_value'];
        $element[$delta]['#markup'] = theme('classy_color', array('color' => $color));
      }
      break;
  }

  return $element;
}*/


function classy_views_api() {
    return array(
        'api' => '3.0-alpha1',
        'path' => drupal_get_path('module','classy'). '/views',
    );
}


/**
 * Implements hook_theme_registry_alter()
 * Want to provide theming tpls here, rather than just in the theme
 */
function classy_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'classy');
  $theme_registry_copy = $theme_registry;       // munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _classy_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter)
 */
function _classy_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

/**
 * Implementation of hook_preprocess_node();
 * 
 * All the additional custom node variables are assembled here.
 */
function classy_preprocess_node(&$vars) {

  //Add view mode theme suggestions
  $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__' . $vars['view_mode'];

  //menu seems to be messed up and not adding active trail via context
  //dpm(context_get());
  //dpm(menu_get_active_trail());
  
  global $base_url;
  //global $language;
  if (isset($vars['type'])) {
    switch ($vars['type']) {
	    case 'profile':
	      unset($vars['content']['links']);
	      unset($vars['content']['comments']);
	      break;
      case 'course':
        break;      
      case 'class':
        
        //Load related course information
        
        //send course info to approval criteria?
        $criteria = classy_approval_criteria($vars['type']);
        foreach ($criteria as $criterion) {
          if ($criterion['pass'] == FALSE) {
            $vars['registration']['text'] = $criterion['text'];
            $vars['registration']['target'] = $base_url . $criterion['target'];
            break;
          }
        }
        break;
	    case 'site_page':
	      unset($vars['content']['links']);
	      unset($vars['content']['comments']);
        break;
      default:
	      break;
    }
  }
}


/**
 * Create the class list
 */
 
 // uses drupal_write_record($table, &$record, $primary_keys = array())
 
 /*    // Initializing $record array with values.
    $record = array (
    "uid" => $user->uid,
    "ufname" => $form_state ["values"]["name"],
    "ufdesc" => $form_state ["values"]["desc"],
    "ufpath" => $path,
    "ufstatus" => 1,
    "ufdate" => $time,
    );
    // Inserting $record (data) into the database. Here $table variable contains the name of the table.
    drupal_write_record ($table, $record);
    // Getting the last inserted ID. (ufid) is the primary key of the table in my scenario.
    $return = $record ['ufid'];
    
  */  
  
//@todo add method for 'approving' registration
  
 
//@todo hook into signup and add check for 'paid' status


/**
 * Creates a hook to specify validation permissions
 *
 * Validation criteria have 3 levels - annonymous, authenticated (can't sign up) and authorized - array
 *
 *
 */
function classy_approval_criteria($type) {
  $criteria = array();
  //user must be logged in
  global $user;
  if ($user->uid) {
    $criteria[] = array('type'=>'logged_in', 'pass'=>TRUE);  
  } else {
    $criteria[] = array('type'=>'logged_in', 'pass'=>FALSE, 'target'=>'/user', 'text' => 'Please Log In',);
  }
  //get all criteria from other modules
  $external_criteria = module_invoke_all('approval_criterion', $type);
  $criteria[] = $external_criteria;
  return $criteria;
}
