<?php

//can I shift $params to a generic set for the user, rather than pushing collection into each function?

function classy_civicrm_menu() {
  $items = array();
  $items['admin/config/classy/civicrm'] = array(
    'title' => 'CiviCRM integration settings',
    'description' => 'Configure Classy to use CiviCRM',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('classy_civicrm_config'),
    'access arguments' => array('administer'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

function classy_civicrm_config() {
  $form = array();
  $form['#tree'] = TRUE;
  $form['classy_civicrm_type'] = array(
    '#title' => t('CiviCRM Contribution Types'),
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
  );
  $types = variable_get('classy_civicrm_type', array());
  $form['classy_civicrm_type']['regular'] = array(
    '#type' => 'textfield',
    '#title' => t('Regular Class Type'),
    '#default_value' => $types['regular'],
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The CiviCRM Contribution Type ID for regular classes."),
    '#required' => TRUE,
  );
  $form['classy_civicrm_type']['special'] = array(
    '#type' => 'textfield',
    '#title' => t('Special Class Type'),
    '#default_value' => $types['special'],
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The CiviCRM Contribution Type ID for special classes."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_block_info()
 */

function classy_civicrm_block_info() {
  $blocks = array();
  $blocks['vouchers'] = array(
    'info' => t('Available Vouchers (User)'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}


/**
 * Implementation of hook_block_view();
 */
 
function classy_civicrm_block_view($delta) {
  if ($delta == 'vouchers') {
    $block_vars = array();
    
    //get information for the available contribution types
    $contribution_types = variable_get('classy_civicrm_type_info');
    
    //create some shit for each possible type
    foreach ($contribution_types as $contribution_type_id=>$contribution_type) {
      $block_vars[$contribution_type_id] = $contribution_type;
    }
    
    //grab the session variable for available user credits    
    $available = classy_civicrm_credit_check_display();  
        
    foreach ($available as $contribution_type_id=>$credit_count) {
      if (array_key_exists($contribution_type_id, $contribution_types)) {
        $block_vars[$contribution_type_id]['count'] = $credit_count;
      }
    }
    $content = theme('classy_vouchers', array('args'=>$block_vars));
    $block = array(
      'subject' => '',
      'content' => $content,
    );
    return $block;
  }
}

/**
 * Implementation of hook_theme()
 */

function classy_civicrm_theme() {
  return array(
    'classy_vouchers' => array(
      'variables' => array($args = NULL),
      'template' => 'classy-vouchers',
    ),
  ); 
}




/** 
 * Aggregates all calls to the CiviCRM API
 */

function _classy_civicrm_initialize_api() {
  $civi_drupal_path = drupal_get_path('module','civicrm');
  $civi_api_path = strstr($civi_drupal_path, 'drupal', true); 
  $civi_api_path .= '/api/api.php';  //@todo add custom directory look, also local
  civicrm_initialize();
  require_once $civi_api_path;
} 


function classy_civicrm_civicrm_post( $op, $objectName, $objectId, &$objectRef ) {
  global $user;
  
  //narrow down to contributions of the correct types
  $contribution_types = array();
  $types = variable_get('classy_civicrm_type');
  foreach ($types as $type) {
    $contribution_types[] = $type;
  }
  
  //check to see if language class contribution type
  if ($objectName == 'Contribution'
    && in_array($objectRef->contribution_type_id, $contribution_types)) {  
    
    _classy_civicrm_initialize_api();

    //$uid = $GLOBALS['user']->uid;  //get drupal user
    $civiuser = $objectRef->contact_id;  //get civi user

    if ($op == 'create') {
      //Check to see if this is paid or waiting  
      $is_paid = ($objectRef->contribution_status_id == 1 ? TRUE : FALSE);
      $params = array(
        'uid' => $user->uid,
        'civiuser' => $civiuser,
        'contribution_id' => $objectId,
        'contribution_type_id' => $objectRef->contribution_type_id,
        'is_paid' => $is_paid,
      );
     
      $added = _classy_civicrm_record_credit($params);
            
    } elseif ($op == 'edit') {
      //check if this edit is updating the payment status
      if ($objectRef->contribution_status_id == 1) {

        //get the old record(s)
        $query = db_select('classy_civicrm_credits', 'c');
        $query
          ->fields('c')
          ->condition('civi_contact_id', $civiuser,'=')
          ->condition('civi_contribution_id', $objectId,'=');
        $credit_records = $query->execute()->fetchAll();
        
        foreach ($credit_records as $credit_record) {
                    
          //update the credits table, mark as paid
          $table = 'classy_civicrm_credits';
          $record = array(
            'id' => $credit_record->id,
            'paid' => 1,
          );  
          drupal_write_record($table, $record, 'id');
        }
      }  elseif ($objectRef->contribution_status_id != 1) {  //no longer paid (e.g. cancelled)
       
        //get the old record
        $query = db_select('classy_civicrm_credits', 'c');
        $query
          ->fields('c')
          ->condition('civi_contact_id', $civiuser, '=')
          ->condition('civi_contribution_id', $objectId,'=');
        $result = $query->execute()->fetchAll();

        foreach ($result as $credit_record) {
          
          $table = 'classy_civicrm_credits';
          $record = array(
            'id' => $credit_record->id,
            'paid' => 0,
          );  
          drupal_write_record($table, $record, 'id');
        }
      }      
    }
    classy_civicrm_credit_check_display(TRUE);    
  }
  
  //if there are multiple purchases they show up as one lump sum and then an insert into the 'civicrm_line_item' table
  // this does not get called on 'edit' only when the contribution is initially made
  if ($objectName == 'LineItem'
    && $objectRef['entity_table'] == 'civicrm_contribution') { 
    //@todo need to add check to reduce to only classy contributions      
    
    _classy_civicrm_initialize_api();
    //only needed if qty is multiple - single has already been added 
    if ((int)$objectRef['qty'] > 1) {
      //get contribution record using the entity_id - we need to know what type it is
      $contributions = civicrm_api('contribution', 'get', array('version'=>3, 'id'=>$objectId));

      $c = 1;
      foreach ($contributions['values'] as $contribution) { 
        while ($c < (int)$objectRef['qty']) {
          $is_paid = ($contribution['contribution_status_id'] == 1 ? TRUE : FALSE);
          $params = array(
            'uid' => $user->uid,
            'civiuser' => $contribution['contact_id'],
            'contribution_id' => $contribution['id'],
            'contribution_type_id' => $contribution['contribution_type_id'],
            'is_paid' => $is_paid,
          );
          
          $added = _classy_civicrm_record_credit($params);
          $c++;
        }
      }
    }
    classy_civicrm_credit_check_display(TRUE);
  }

}


function _classy_civicrm_record_credit( $params ){
  //add language contributions to credits table
  $table = 'classy_civicrm_credits';
  $record = array(
    'drupal_uid' => $params['uid'],
    'civi_contact_id' => $params['civiuser'],
    'civi_contribution_id' => $params['contribution_id'],
    'civi_contribution_type_id' => $params['contribution_type_id'],
    'paid' => $params['is_paid'],
    'used' => 0,
  );
  drupal_write_record($table, $record);
}


/**
 * CiviCRM get contact -- currently not used
 */
function classy_civicrm_contact($uid = NULL) {
  if (!$uid) {
    $uid = $GLOBALS['user']->uid;
  }
  //@todo breaks on anon user  
  //Get current user civicrm id - use uf_match to get the contact based on drupal user
  $contact = civicrm_api('UFMatch', 'get', array('version' => 3, 'uf_id' => $uid));
  foreach ($contact['values'] as $drupal_user){
    $civiuser = civicrm_api('contact' , 'get', array('version' => 3, 'id' => $drupal_user['contact_id']));
  }
  return $civiuser;
}

/**
 * CiviCRM get contribution
 *
 * Get class contributions for civi user  -- currently useless
 */ 

function classy_civicrm_contribution_credits($civiuser, $contribution_id = NULL){
  
  /* 
  // available params  
          'contact_id' => '1',
          'contact_type' => 'Individual',
          'sort_name' => 'Anderson, Anthony',
          'display_name' => 'Anthony Anderson',
          'contribution_id' => '1',
          'currency' => 'USD',
          'receive_date' => '2010-01-20 00:00:00',
          'non_deductible_amount' => '10.00',
          'total_amount' => '100.00',
          'fee_amount' => '51.00',
          'net_amount' => '91.00',
          'trxn_id' => '23456',
          'invoice_id' => '78910',
          'contribution_source' => 'SSF',
          'is_test' => 0,
          'is_pay_later' => 0,
          'contribution_type_id' => '11',
          'contribution_type' => 'Prize',
          'accounting_code' => '1005',
          'contribution_status_id' => '1',
          'contribution_status' => 'Completed',
          'id' => '1',
  */
  $params = array('version' => 3, 'contact_id' => $civiuser['id']);
  if ($contribution_id) {
    $params['contribution_id'] = $contribution_id;
  }
  $contributions = civicrm_api( 'contribution', 'get', $params );
  return $contributions;
}


 
/**
 * Add CiviCRM approval Criterion
 */
 
function classy_civicrm_approval_criterion($type, $nid, $uid) {

  //added criteria - entry in 'credits' table   ---contribution type is different from contribution page
  if ($type == 'class') {
    $contrib_type = '5';
    $contrib_page = '4';
  } else { //tutoring
    $contrib_type = '6';
    $contrib_page = '3';
  }
  
  //get the current node - checking against this overriding 'withdraw'
  $query = db_select('classy_enrollment', 'e');
  $query
    ->fields('e')
    ->condition('student_id', $uid,'=')
    ->condition('class_id', $nid, '=')
    ->condition('state', 1, '=');
  $result = $query->execute()->fetchAssoc();

  if ($result) {
    $criterion = array('type' => 'has_credit', 'pass' => TRUE);
  } else {
    
    //check credits table for 'paid', !'used' entries for the selected contrib_id
    $query = db_select('classy_civicrm_credits', 'c');
    $query
      ->fields('c')
      ->condition('drupal_uid', $uid,'=')
      ->condition('civi_contribution_type_id', $contrib_type, '=')
      ->condition('paid', 1, '=')
      ->condition('used', 0, '=');
    $result = $query->execute()->fetchAll();
    $num_credits = count($result);
    $credit = ($num_credits > 0 ? TRUE : FALSE);

    if ($credit == TRUE) {
      $criterion = array('type' => 'has_credit', 'pass' => TRUE);
    } else {
      $criterion = array('type' => 'has_credit', 'pass' => FALSE, 'target' => '/civicrm/contribute/transact?reset=1&id=' . $contrib_page, 'text'=> '.');
    }
  
  }
  return $criterion;
  
}

/** 
 * Implementation of hook_form_alter
 */
function classy_civicrm_form_alter(&$form, &$form_state, $form_id) {

  $enroll_forms = array('classy_enroll', 'classy_withdraw');
  if (in_array($form['#form_id'], $enroll_forms)){
    $form['#submit'][] = 'classy_civicrm_enrollment_enroll';
  } elseif ($form_id == 'classy_civicrm_config') {
    $form['#submit'][] = 'classy_civicrm_config_helper';
  }
  
}

function classy_civicrm_enrollment_enroll($form, &$form_state) {   
  global $user;
  $uid = $user->uid;
   //make sure not already enrolled or withdrawn
  if ($form['#form_id'] == 'classy_withdraw') {  
      //get the user's credit history
    $query = db_select('classy_civicrm_credits', 'c');
    $query
      ->fields('c')
      ->condition('drupal_uid', $uid,'=')
      //->condition('civi_contribution_type_id', $contrib_type, '=')  // need to add type check back in
      ->condition('paid', 1, '=')
      ->condition('used', 1, '=');
    $result = $query->execute()->fetchAssoc();
    $credit_id = $result['id'];
       
    
    $table = 'classy_civicrm_credits';
    $record = array(
      'id' => $credit_id,
      'drupal_uid' => $uid,
      'used' => 0,
    );  
    drupal_write_record($table, $record, 'id');
  }
  if ($form['#form_id'] == 'classy_enroll') {

    //if we've gotten here, then we have at least 1 credit to spend ??
    //get an available credit for the user
    $query = db_select('classy_civicrm_credits', 'c');
    $query
      ->fields('c')
      ->condition('drupal_uid', $uid,'=')
      //->condition('civi_contribution_type_id', $contrib_type, '=')  // need to add type check back in
      ->condition('paid', 1, '=')
      ->condition('used', 0, '=');
    $result = $query->execute()->fetchAssoc();
    $credit_id = $result['id'];

    $table = 'classy_civicrm_credits';
    $record = array(
      'id' => $credit_id,
      'drupal_id' => $uid,
      'used' => 1,
    );  
    drupal_write_record($table, $record, 'id');
  }
  classy_civicrm_credit_check_display(TRUE); 
}

function classy_civicrm_config_helper($form, &$form_state) {
  $types = array();
  //initialize api
  _classy_civicrm_initialize_api();
  
  foreach ($form_state['values']['classy_civicrm_type'] as $name=>$type){
    //get the name and description for each class type from civi
    $query = "SELECT * FROM civicrm_contribution_type WHERE id=" . $type;
    $dao =& CRM_Core_DAO::executeQuery($query);
    while($dao->fetch()) {
      $types[$dao->id] = array('name'=>$dao->name);
    }
    foreach ($types as $key=>$value) {
      $query = "SELECT * FROM civicrm_contribution_page WHERE contribution_type_id=" . $key;
      $dao =& CRM_Core_DAO::executeQuery($query);
      while ($dao->fetch()) {
        $types[$key]['contribution_page'] = $dao->id;
      }
    }

  }
  variable_set('classy_civicrm_type_info', $types);

}


function classy_civicrm_credit_check_display($reset = NULL) {
  $available = array();  

  //check to see if this is a first load
  if (!isset($_SESSION['classy_credits'])) {
    $build = TRUE;
  } 

  if (!is_null($reset) || isset($build)) {  //needs to be rebuilt
    
    //get the current user and contribution types
    global $user;
    $contribution_types = array();
    $types = variable_get('classy_civicrm_type');
    foreach ($types as $type) {
      $contribution_types[] = $type;
    }

    //query credits table for all credit types to find # available (paid)
    $query = db_select('classy_civicrm_credits', 'c');
    $query
      ->fields('c')
      ->condition('drupal_uid', $user->uid, '=')
      ->condition('civi_contribution_type_id', $contribution_types,'IN');
    $result = $query->execute()->fetchAll();
    
    foreach ($result as $credit) {
      if (!array_key_exists($credit->civi_contribution_type_id, $available)) {
          $available[$credit->civi_contribution_type_id]['unpaid'] = 0;
          $available[$credit->civi_contribution_type_id]['open'] = 0;
      }        
      if ($credit->paid == 1 && $credit->used == 0) {
        $available[$credit->civi_contribution_type_id]['open']++;
      } elseif ($credit->paid == 0 && $credit->used == 0) {
        $available[$credit->civi_contribution_type_id]['unpaid']++;
      }
    }
    //add to session variable for the next page load
    $_SESSION['classy_credits'] = $available;
  } else {
    foreach ($_SESSION['classy_credits'] as $key=>$credit_count) {
      $available[$key] = $credit_count;
    }
  }

  return $available;
}


//////////////migration stuff///////////////////
/*
INSERT INTO classy_civicrm_credits 
  (drupal_uid,civi_contact_id,civi_contribution_id,civi_contribution_type_id,paid,used)
  VALUES
  (1,1,8,4,1,0),
  (1,1,7,4,0,0),
  (1,1,6,4,1,0),
  (1,1,4,4,0,0),
  (1,1,8,4,1,0);
  
*/

