<?php

$view = new view;
$view->name = 'classes';
$view->description = '';
$view->tag = 'default';
$view->base_table = 'node';
$view->human_name = 'Classes';
$view->core = 7;
$view->api_version = '3.0';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

/* Display: Master */
$handler = $view->new_display('default', 'Master', 'default');
$handler->display->display_options['title'] = 'Available Classes';
$handler->display->display_options['use_ajax'] = TRUE;
$handler->display->display_options['access']['type'] = 'perm';
$handler->display->display_options['access']['perm'] = 'access administration pages';
$handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['query']['type'] = 'views_query';
$handler->display->display_options['query']['options']['query_comment'] = FALSE;
$handler->display->display_options['exposed_form']['type'] = 'basic';
$handler->display->display_options['pager']['type'] = 'full';
$handler->display->display_options['pager']['options']['items_per_page'] = '10';
$handler->display->display_options['style_plugin'] = 'list';
$handler->display->display_options['row_plugin'] = 'fields';
/* Relationship: Entity Reference: Referenced Entity */
$handler->display->display_options['relationships']['classy_course_id_target_id']['id'] = 'classy_course_id_target_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['table'] = 'field_data_classy_course_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['field'] = 'classy_course_id_target_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['label'] = 'Course';
$handler->display->display_options['relationships']['classy_course_id_target_id']['required'] = 1;
/* Relationship: Entity Reference: Referenced Entity */
$handler->display->display_options['relationships']['classy_room_id_target_id']['id'] = 'classy_room_id_target_id';
$handler->display->display_options['relationships']['classy_room_id_target_id']['table'] = 'field_data_classy_room_id';
$handler->display->display_options['relationships']['classy_room_id_target_id']['field'] = 'classy_room_id_target_id';
$handler->display->display_options['relationships']['classy_room_id_target_id']['label'] = 'Room';
$handler->display->display_options['relationships']['classy_room_id_target_id']['required'] = 0;
/* Relationship: Entity Reference: Referenced Entity */
$handler->display->display_options['relationships']['classy_teacher_id_target_id']['id'] = 'classy_teacher_id_target_id';
$handler->display->display_options['relationships']['classy_teacher_id_target_id']['table'] = 'field_data_classy_teacher_id';
$handler->display->display_options['relationships']['classy_teacher_id_target_id']['field'] = 'classy_teacher_id_target_id';
$handler->display->display_options['relationships']['classy_teacher_id_target_id']['label'] = 'Teacher';
$handler->display->display_options['relationships']['classy_teacher_id_target_id']['required'] = 0;
/* Field: Content: Title */
$handler->display->display_options['fields']['title_1']['id'] = 'title_1';
$handler->display->display_options['fields']['title_1']['table'] = 'node';
$handler->display->display_options['fields']['title_1']['field'] = 'title';
$handler->display->display_options['fields']['title_1']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['fields']['title_1']['label'] = 'Course';
$handler->display->display_options['fields']['title_1']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['external'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['title_1']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['title_1']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['trim'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['html'] = 0;
$handler->display->display_options['fields']['title_1']['element_label_colon'] = 0;
$handler->display->display_options['fields']['title_1']['element_default_classes'] = 1;
$handler->display->display_options['fields']['title_1']['hide_empty'] = 0;
$handler->display->display_options['fields']['title_1']['empty_zero'] = 0;
$handler->display->display_options['fields']['title_1']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['title_1']['link_to_node'] = 1;
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['label'] = 'Class';
$handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['title']['alter']['external'] = 0;
$handler->display->display_options['fields']['title']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['title']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
$handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
$handler->display->display_options['fields']['title']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim'] = 0;
$handler->display->display_options['fields']['title']['alter']['html'] = 0;
$handler->display->display_options['fields']['title']['element_label_colon'] = 0;
$handler->display->display_options['fields']['title']['element_default_classes'] = 1;
$handler->display->display_options['fields']['title']['hide_empty'] = 0;
$handler->display->display_options['fields']['title']['empty_zero'] = 0;
$handler->display->display_options['fields']['title']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['title']['link_to_node'] = 1;
/* Field: Content: Time */
$handler->display->display_options['fields']['classy_time_id']['id'] = 'classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['table'] = 'field_data_classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['field'] = 'classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['external'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['classy_time_id']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['classy_time_id']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['trim'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['html'] = 0;
$handler->display->display_options['fields']['classy_time_id']['element_label_colon'] = 1;
$handler->display->display_options['fields']['classy_time_id']['element_default_classes'] = 1;
$handler->display->display_options['fields']['classy_time_id']['hide_empty'] = 0;
$handler->display->display_options['fields']['classy_time_id']['empty_zero'] = 0;
$handler->display->display_options['fields']['classy_time_id']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['classy_time_id']['field_api_classes'] = 0;
/* Field: Node: Link */
$handler->display->display_options['fields']['view_node']['id'] = 'view_node';
$handler->display->display_options['fields']['view_node']['table'] = 'views_entity_node';
$handler->display->display_options['fields']['view_node']['field'] = 'view_node';
$handler->display->display_options['fields']['view_node']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['view_node']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['view_node']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['trim'] = 0;
$handler->display->display_options['fields']['view_node']['alter']['html'] = 0;
$handler->display->display_options['fields']['view_node']['element_label_colon'] = 1;
$handler->display->display_options['fields']['view_node']['element_default_classes'] = 1;
$handler->display->display_options['fields']['view_node']['hide_empty'] = 0;
$handler->display->display_options['fields']['view_node']['empty_zero'] = 0;
$handler->display->display_options['fields']['view_node']['hide_alter_empty'] = 1;
/* Sort criterion: Content: Title */
$handler->display->display_options['sorts']['title']['id'] = 'title';
$handler->display->display_options['sorts']['title']['table'] = 'node';
$handler->display->display_options['sorts']['title']['field'] = 'title';
$handler->display->display_options['sorts']['title']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['sorts']['title']['expose']['label'] = 'Title';
/* Filter criterion: Content: Published */
$handler->display->display_options['filters']['status']['id'] = 'status';
$handler->display->display_options['filters']['status']['table'] = 'node';
$handler->display->display_options['filters']['status']['field'] = 'status';
$handler->display->display_options['filters']['status']['value'] = 1;
$handler->display->display_options['filters']['status']['group'] = 1;
$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
/* Filter criterion: Content: Type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'node';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'class' => 'class',
);
/* Filter criterion: Content: Language (classy_language_id) */
$handler->display->display_options['filters']['classy_language_id_target_id']['id'] = 'classy_language_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['table'] = 'field_data_classy_language_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['field'] = 'classy_language_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['exposed'] = TRUE;
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['operator_id'] = 'classy_language_id_target_id_op';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['label'] = 'Language';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['operator'] = 'classy_language_id_target_id_op';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['identifier'] = 'classy_language_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['reduce'] = 0;
/* Filter criterion: Content: Level (classy_level_id) */
$handler->display->display_options['filters']['classy_level_id_target_id']['id'] = 'classy_level_id_target_id';
$handler->display->display_options['filters']['classy_level_id_target_id']['table'] = 'field_data_classy_level_id';
$handler->display->display_options['filters']['classy_level_id_target_id']['field'] = 'classy_level_id_target_id';
$handler->display->display_options['filters']['classy_level_id_target_id']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['filters']['classy_level_id_target_id']['exposed'] = TRUE;
$handler->display->display_options['filters']['classy_level_id_target_id']['expose']['operator_id'] = 'classy_level_id_target_id_op';
$handler->display->display_options['filters']['classy_level_id_target_id']['expose']['label'] = 'Level';
$handler->display->display_options['filters']['classy_level_id_target_id']['expose']['operator'] = 'classy_level_id_target_id_op';
$handler->display->display_options['filters']['classy_level_id_target_id']['expose']['identifier'] = 'classy_level_id_target_id';
$handler->display->display_options['filters']['classy_level_id_target_id']['expose']['reduce'] = 0;
/* Filter criterion: Content: Time (classy_time_id) */
$handler->display->display_options['filters']['classy_time_id_target_id']['id'] = 'classy_time_id_target_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['table'] = 'field_data_classy_time_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['field'] = 'classy_time_id_target_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['exposed'] = TRUE;
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['operator_id'] = 'classy_time_id_target_id_op';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['label'] = 'Time ';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['operator'] = 'classy_time_id_target_id_op';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['identifier'] = 'classy_time_id_target_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['reduce'] = 0;

/* Display: Admin */
$handler = $view->new_display('page', 'Admin', 'admin');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Current Classes';
$handler->display->display_options['defaults']['style_plugin'] = FALSE;
$handler->display->display_options['style_plugin'] = 'table';
$handler->display->display_options['style_options']['columns'] = array(
  'title' => 'title',
  'body' => 'body',
  'classy_time_id' => 'classy_time_id',
  'classy_teacher_id' => 'classy_teacher_id',
  'classy_room_id' => 'classy_room_id',
);
$handler->display->display_options['style_options']['default'] = '-1';
$handler->display->display_options['style_options']['info'] = array(
  'title' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'body' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'classy_time_id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'classy_teacher_id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'classy_room_id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
);
$handler->display->display_options['style_options']['override'] = 1;
$handler->display->display_options['style_options']['sticky'] = 0;
$handler->display->display_options['style_options']['empty_table'] = 0;
$handler->display->display_options['defaults']['style_options'] = FALSE;
$handler->display->display_options['defaults']['row_plugin'] = FALSE;
$handler->display->display_options['defaults']['row_options'] = FALSE;
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: Content: Title */
$handler->display->display_options['fields']['title_1']['id'] = 'title_1';
$handler->display->display_options['fields']['title_1']['table'] = 'node';
$handler->display->display_options['fields']['title_1']['field'] = 'title';
$handler->display->display_options['fields']['title_1']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['fields']['title_1']['label'] = 'Course';
$handler->display->display_options['fields']['title_1']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['external'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['title_1']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['title_1']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['trim'] = 0;
$handler->display->display_options['fields']['title_1']['alter']['html'] = 0;
$handler->display->display_options['fields']['title_1']['element_label_colon'] = 0;
$handler->display->display_options['fields']['title_1']['element_default_classes'] = 1;
$handler->display->display_options['fields']['title_1']['hide_empty'] = 0;
$handler->display->display_options['fields']['title_1']['empty_zero'] = 0;
$handler->display->display_options['fields']['title_1']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['title_1']['link_to_node'] = 0;
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['label'] = 'Class';
$handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['title']['alter']['external'] = 0;
$handler->display->display_options['fields']['title']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['title']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['title']['alter']['word_boundary'] = 0;
$handler->display->display_options['fields']['title']['alter']['ellipsis'] = 0;
$handler->display->display_options['fields']['title']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim'] = 0;
$handler->display->display_options['fields']['title']['alter']['html'] = 0;
$handler->display->display_options['fields']['title']['element_label_colon'] = 0;
$handler->display->display_options['fields']['title']['element_default_classes'] = 1;
$handler->display->display_options['fields']['title']['hide_empty'] = 0;
$handler->display->display_options['fields']['title']['empty_zero'] = 0;
$handler->display->display_options['fields']['title']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['title']['link_to_node'] = 0;
/* Field: Content: Time */
$handler->display->display_options['fields']['classy_time_id']['id'] = 'classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['table'] = 'field_data_classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['field'] = 'classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['external'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['classy_time_id']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['classy_time_id']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['trim'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['html'] = 0;
$handler->display->display_options['fields']['classy_time_id']['element_label_colon'] = 1;
$handler->display->display_options['fields']['classy_time_id']['element_default_classes'] = 1;
$handler->display->display_options['fields']['classy_time_id']['hide_empty'] = 0;
$handler->display->display_options['fields']['classy_time_id']['empty_zero'] = 0;
$handler->display->display_options['fields']['classy_time_id']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['classy_time_id']['field_api_classes'] = 0;
/* Field: Taxonomy term: Name */
$handler->display->display_options['fields']['name']['id'] = 'name';
$handler->display->display_options['fields']['name']['table'] = 'taxonomy_term_data';
$handler->display->display_options['fields']['name']['field'] = 'name';
$handler->display->display_options['fields']['name']['relationship'] = 'classy_room_id_target_id';
$handler->display->display_options['fields']['name']['label'] = 'Room';
$handler->display->display_options['fields']['name']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['name']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['name']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['name']['alter']['external'] = 0;
$handler->display->display_options['fields']['name']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['name']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['name']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['name']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['name']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['name']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['name']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['name']['alter']['trim'] = 0;
$handler->display->display_options['fields']['name']['alter']['html'] = 0;
$handler->display->display_options['fields']['name']['element_label_colon'] = 0;
$handler->display->display_options['fields']['name']['element_default_classes'] = 1;
$handler->display->display_options['fields']['name']['hide_empty'] = 0;
$handler->display->display_options['fields']['name']['empty_zero'] = 0;
$handler->display->display_options['fields']['name']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['name']['link_to_taxonomy'] = 0;
$handler->display->display_options['fields']['name']['convert_spaces'] = 0;
/* Field: User: Name */
$handler->display->display_options['fields']['name_1']['id'] = 'name_1';
$handler->display->display_options['fields']['name_1']['table'] = 'users';
$handler->display->display_options['fields']['name_1']['field'] = 'name';
$handler->display->display_options['fields']['name_1']['relationship'] = 'classy_teacher_id_target_id';
$handler->display->display_options['fields']['name_1']['label'] = 'Teacher';
$handler->display->display_options['fields']['name_1']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['external'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['name_1']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['name_1']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['trim'] = 0;
$handler->display->display_options['fields']['name_1']['alter']['html'] = 0;
$handler->display->display_options['fields']['name_1']['element_label_colon'] = 0;
$handler->display->display_options['fields']['name_1']['element_default_classes'] = 1;
$handler->display->display_options['fields']['name_1']['hide_empty'] = 0;
$handler->display->display_options['fields']['name_1']['empty_zero'] = 0;
$handler->display->display_options['fields']['name_1']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['name_1']['link_to_user'] = 1;
$handler->display->display_options['fields']['name_1']['overwrite_anonymous'] = 0;
$handler->display->display_options['fields']['name_1']['format_username'] = 1;
/* Field: Content: Nid */
$handler->display->display_options['fields']['nid']['id'] = 'nid';
$handler->display->display_options['fields']['nid']['table'] = 'node';
$handler->display->display_options['fields']['nid']['field'] = 'nid';
$handler->display->display_options['fields']['nid']['label'] = '';
$handler->display->display_options['fields']['nid']['exclude'] = TRUE;
$handler->display->display_options['fields']['nid']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['nid']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['nid']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['nid']['alter']['external'] = 0;
$handler->display->display_options['fields']['nid']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['nid']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['nid']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['nid']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['nid']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['nid']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['nid']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['nid']['alter']['trim'] = 0;
$handler->display->display_options['fields']['nid']['alter']['html'] = 0;
$handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
$handler->display->display_options['fields']['nid']['element_default_classes'] = 1;
$handler->display->display_options['fields']['nid']['hide_empty'] = 0;
$handler->display->display_options['fields']['nid']['empty_zero'] = 0;
$handler->display->display_options['fields']['nid']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['nid']['link_to_node'] = 0;
/* Field: Global: Custom text */
$handler->display->display_options['fields']['nothing']['id'] = 'nothing';
$handler->display->display_options['fields']['nothing']['table'] = 'views';
$handler->display->display_options['fields']['nothing']['field'] = 'nothing';
$handler->display->display_options['fields']['nothing']['label'] = 'View Class';
$handler->display->display_options['fields']['nothing']['alter']['text'] = 'View';
$handler->display->display_options['fields']['nothing']['alter']['make_link'] = 1;
$handler->display->display_options['fields']['nothing']['alter']['path'] = 'admin/classy/class/[nid]';
$handler->display->display_options['fields']['nothing']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['external'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['nothing']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['nothing']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['trim'] = 0;
$handler->display->display_options['fields']['nothing']['alter']['html'] = 0;
$handler->display->display_options['fields']['nothing']['element_label_colon'] = 0;
$handler->display->display_options['fields']['nothing']['element_default_classes'] = 1;
$handler->display->display_options['fields']['nothing']['hide_empty'] = 0;
$handler->display->display_options['fields']['nothing']['empty_zero'] = 0;
$handler->display->display_options['fields']['nothing']['hide_alter_empty'] = 0;
$handler->display->display_options['defaults']['filters'] = FALSE;
/* Filter criterion: Content: Published */
$handler->display->display_options['filters']['status']['id'] = 'status';
$handler->display->display_options['filters']['status']['table'] = 'node';
$handler->display->display_options['filters']['status']['field'] = 'status';
$handler->display->display_options['filters']['status']['value'] = 1;
$handler->display->display_options['filters']['status']['group'] = 1;
$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
/* Filter criterion: Content: Type */
$handler->display->display_options['filters']['type']['id'] = 'type';
$handler->display->display_options['filters']['type']['table'] = 'node';
$handler->display->display_options['filters']['type']['field'] = 'type';
$handler->display->display_options['filters']['type']['value'] = array(
  'class' => 'class',
);
$handler->display->display_options['filters']['type']['group'] = 1;
/* Filter criterion: Content: Year (classy_year_id) */
$handler->display->display_options['filters']['classy_year_id_target_id']['id'] = 'classy_year_id_target_id';
$handler->display->display_options['filters']['classy_year_id_target_id']['table'] = 'field_data_classy_year_id';
$handler->display->display_options['filters']['classy_year_id_target_id']['field'] = 'classy_year_id_target_id';
$handler->display->display_options['filters']['classy_year_id_target_id']['group'] = 1;
$handler->display->display_options['filters']['classy_year_id_target_id']['exposed'] = TRUE;
$handler->display->display_options['filters']['classy_year_id_target_id']['expose']['operator_id'] = 'classy_year_id_target_id_op';
$handler->display->display_options['filters']['classy_year_id_target_id']['expose']['label'] = 'Year';
$handler->display->display_options['filters']['classy_year_id_target_id']['expose']['operator'] = 'classy_year_id_target_id_op';
$handler->display->display_options['filters']['classy_year_id_target_id']['expose']['identifier'] = 'classy_year_id_target_id';
$handler->display->display_options['filters']['classy_year_id_target_id']['expose']['reduce'] = 0;
/* Filter criterion: Content: Semester (classy_semester_id) */
$handler->display->display_options['filters']['classy_semester_id_target_id']['id'] = 'classy_semester_id_target_id';
$handler->display->display_options['filters']['classy_semester_id_target_id']['table'] = 'field_data_classy_semester_id';
$handler->display->display_options['filters']['classy_semester_id_target_id']['field'] = 'classy_semester_id_target_id';
$handler->display->display_options['filters']['classy_semester_id_target_id']['group'] = 1;
$handler->display->display_options['filters']['classy_semester_id_target_id']['exposed'] = TRUE;
$handler->display->display_options['filters']['classy_semester_id_target_id']['expose']['operator_id'] = 'classy_semester_id_target_id_op';
$handler->display->display_options['filters']['classy_semester_id_target_id']['expose']['label'] = 'Semester';
$handler->display->display_options['filters']['classy_semester_id_target_id']['expose']['operator'] = 'classy_semester_id_target_id_op';
$handler->display->display_options['filters']['classy_semester_id_target_id']['expose']['identifier'] = 'classy_semester_id_target_id';
$handler->display->display_options['filters']['classy_semester_id_target_id']['expose']['reduce'] = 0;
/* Filter criterion: Content: Time (classy_time_id) */
$handler->display->display_options['filters']['classy_time_id_target_id']['id'] = 'classy_time_id_target_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['table'] = 'field_data_classy_time_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['field'] = 'classy_time_id_target_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['group'] = 1;
$handler->display->display_options['filters']['classy_time_id_target_id']['exposed'] = TRUE;
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['operator_id'] = 'classy_time_id_target_id_op';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['label'] = 'Time';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['operator'] = 'classy_time_id_target_id_op';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['identifier'] = 'classy_time_id_target_id';
$handler->display->display_options['filters']['classy_time_id_target_id']['expose']['reduce'] = 0;
/* Filter criterion: Content: Language (classy_language_id) */
$handler->display->display_options['filters']['classy_language_id_target_id']['id'] = 'classy_language_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['table'] = 'field_data_classy_language_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['field'] = 'classy_language_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['group'] = 1;
$handler->display->display_options['filters']['classy_language_id_target_id']['exposed'] = TRUE;
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['operator_id'] = 'classy_language_id_target_id_op';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['label'] = 'Language';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['operator'] = 'classy_language_id_target_id_op';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['identifier'] = 'classy_language_id_target_id';
$handler->display->display_options['filters']['classy_language_id_target_id']['expose']['reduce'] = 0;
/* Filter criterion: Content: Title */
$handler->display->display_options['filters']['title']['id'] = 'title';
$handler->display->display_options['filters']['title']['table'] = 'node';
$handler->display->display_options['filters']['title']['field'] = 'title';
$handler->display->display_options['filters']['title']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['filters']['title']['group'] = 1;
$handler->display->display_options['filters']['title']['exposed'] = TRUE;
$handler->display->display_options['filters']['title']['expose']['operator_id'] = 'title_op';
$handler->display->display_options['filters']['title']['expose']['label'] = 'Course';
$handler->display->display_options['filters']['title']['expose']['operator'] = 'title_op';
$handler->display->display_options['filters']['title']['expose']['identifier'] = 'title';
$handler->display->display_options['filters']['title']['expose']['required'] = 0;
$handler->display->display_options['filters']['title']['expose']['multiple'] = FALSE;
$handler->display->display_options['path'] = 'admin/classy/active';
$handler->display->display_options['menu']['type'] = 'tab';
$handler->display->display_options['menu']['title'] = 'Classes';
$handler->display->display_options['menu']['weight'] = '0';
$handler->display->display_options['menu']['context'] = 0;

/* Display: Public */
$handler = $view->new_display('page', 'Public', 'public');
$handler->display->display_options['defaults']['style_plugin'] = FALSE;
$handler->display->display_options['style_plugin'] = 'table';
$handler->display->display_options['style_options']['columns'] = array(
  'title' => 'title',
  'body' => 'body',
  'classy_time_id' => 'classy_time_id',
  'classy_teacher_id' => 'classy_teacher_id',
  'classy_room_id' => 'classy_room_id',
);
$handler->display->display_options['style_options']['default'] = '-1';
$handler->display->display_options['style_options']['info'] = array(
  'title' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'body' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'classy_time_id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'classy_teacher_id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
  'classy_room_id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
);
$handler->display->display_options['style_options']['override'] = 1;
$handler->display->display_options['style_options']['sticky'] = 0;
$handler->display->display_options['style_options']['empty_table'] = 0;
$handler->display->display_options['defaults']['style_options'] = FALSE;
$handler->display->display_options['defaults']['row_plugin'] = FALSE;
$handler->display->display_options['defaults']['row_options'] = FALSE;
$handler->display->display_options['defaults']['relationships'] = FALSE;
/* Relationship: Entity Reference: Referenced Entity */
$handler->display->display_options['relationships']['classy_course_id_target_id']['id'] = 'classy_course_id_target_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['table'] = 'field_data_classy_course_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['field'] = 'classy_course_id_target_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['label'] = 'Course';
$handler->display->display_options['relationships']['classy_course_id_target_id']['required'] = 1;
$handler->display->display_options['path'] = 'classes';
$handler->display->display_options['menu']['title'] = 'Check';
$handler->display->display_options['menu']['weight'] = '0';
$handler->display->display_options['menu']['name'] = 'management';
$handler->display->display_options['menu']['context'] = 0;
