<?php

$view = new view;
$view->name = 'students';
$view->description = '';
$view->tag = 'default';
$view->base_table = 'classy_grades';
$view->human_name = 'Student Grades';
$view->core = 7;
$view->api_version = '3.0';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

/* Display: Master */
$handler = $view->new_display('default', 'Master', 'default');
$handler->display->display_options['title'] = 'Student Grades';
$handler->display->display_options['use_ajax'] = TRUE;
$handler->display->display_options['access']['type'] = 'none';
$handler->display->display_options['cache']['type'] = 'none';
$handler->display->display_options['query']['type'] = 'views_query';
$handler->display->display_options['query']['options']['query_comment'] = FALSE;
$handler->display->display_options['exposed_form']['type'] = 'basic';
$handler->display->display_options['pager']['type'] = 'full';
$handler->display->display_options['pager']['options']['items_per_page'] = '10';
$handler->display->display_options['style_plugin'] = 'table';
$handler->display->display_options['style_options']['columns'] = array(
  'student_id' => 'student_id',
);
$handler->display->display_options['style_options']['default'] = '-1';
$handler->display->display_options['style_options']['info'] = array(
  'student_id' => array(
    'sortable' => 0,
    'default_sort_order' => 'asc',
    'align' => '',
    'separator' => '',
    'empty_column' => 0,
  ),
);
$handler->display->display_options['style_options']['override'] = 1;
$handler->display->display_options['style_options']['sticky'] = 0;
$handler->display->display_options['style_options']['empty_table'] = 0;
/* Relationship: Classy: Class Reference */
$handler->display->display_options['relationships']['class_id']['id'] = 'class_id';
$handler->display->display_options['relationships']['class_id']['table'] = 'classy_grades';
$handler->display->display_options['relationships']['class_id']['field'] = 'class_id';
$handler->display->display_options['relationships']['class_id']['required'] = 0;
/* Relationship: Classy: Student Reference */
$handler->display->display_options['relationships']['student_id']['id'] = 'student_id';
$handler->display->display_options['relationships']['student_id']['table'] = 'classy_grades';
$handler->display->display_options['relationships']['student_id']['field'] = 'student_id';
$handler->display->display_options['relationships']['student_id']['required'] = 0;
/* Relationship: Entity Reference: Referenced Entity */
$handler->display->display_options['relationships']['classy_course_id_target_id']['id'] = 'classy_course_id_target_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['table'] = 'field_data_classy_course_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['field'] = 'classy_course_id_target_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['relationship'] = 'class_id';
$handler->display->display_options['relationships']['classy_course_id_target_id']['label'] = 'Course';
$handler->display->display_options['relationships']['classy_course_id_target_id']['required'] = 0;
/* Field: User: Name */
$handler->display->display_options['fields']['name']['id'] = 'name';
$handler->display->display_options['fields']['name']['table'] = 'users';
$handler->display->display_options['fields']['name']['field'] = 'name';
$handler->display->display_options['fields']['name']['relationship'] = 'student_id';
$handler->display->display_options['fields']['name']['label'] = 'Student';
$handler->display->display_options['fields']['name']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['name']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['name']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['name']['alter']['external'] = 0;
$handler->display->display_options['fields']['name']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['name']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['name']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['name']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['name']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['name']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['name']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['name']['alter']['trim'] = 0;
$handler->display->display_options['fields']['name']['alter']['html'] = 0;
$handler->display->display_options['fields']['name']['element_label_colon'] = 0;
$handler->display->display_options['fields']['name']['element_default_classes'] = 1;
$handler->display->display_options['fields']['name']['hide_empty'] = 0;
$handler->display->display_options['fields']['name']['empty_zero'] = 0;
$handler->display->display_options['fields']['name']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['name']['link_to_user'] = 1;
$handler->display->display_options['fields']['name']['overwrite_anonymous'] = 0;
$handler->display->display_options['fields']['name']['format_username'] = 1;
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['fields']['title']['label'] = 'Course';
$handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['title']['alter']['external'] = 0;
$handler->display->display_options['fields']['title']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['title']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['title']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['title']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['title']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim'] = 0;
$handler->display->display_options['fields']['title']['alter']['html'] = 0;
$handler->display->display_options['fields']['title']['element_label_colon'] = 0;
$handler->display->display_options['fields']['title']['element_default_classes'] = 1;
$handler->display->display_options['fields']['title']['hide_empty'] = 0;
$handler->display->display_options['fields']['title']['empty_zero'] = 0;
$handler->display->display_options['fields']['title']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['title']['link_to_node'] = 0;
/* Field: Content: Year */
$handler->display->display_options['fields']['classy_year_id']['id'] = 'classy_year_id';
$handler->display->display_options['fields']['classy_year_id']['table'] = 'field_data_classy_year_id';
$handler->display->display_options['fields']['classy_year_id']['field'] = 'classy_year_id';
$handler->display->display_options['fields']['classy_year_id']['relationship'] = 'class_id';
$handler->display->display_options['fields']['classy_year_id']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['external'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['classy_year_id']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['classy_year_id']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['trim'] = 0;
$handler->display->display_options['fields']['classy_year_id']['alter']['html'] = 0;
$handler->display->display_options['fields']['classy_year_id']['element_label_colon'] = 0;
$handler->display->display_options['fields']['classy_year_id']['element_default_classes'] = 1;
$handler->display->display_options['fields']['classy_year_id']['hide_empty'] = 0;
$handler->display->display_options['fields']['classy_year_id']['empty_zero'] = 0;
$handler->display->display_options['fields']['classy_year_id']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['classy_year_id']['settings'] = array(
  'link' => 0,
);
$handler->display->display_options['fields']['classy_year_id']['field_api_classes'] = 0;
/* Field: Content: Semester */
$handler->display->display_options['fields']['classy_semester_id']['id'] = 'classy_semester_id';
$handler->display->display_options['fields']['classy_semester_id']['table'] = 'field_data_classy_semester_id';
$handler->display->display_options['fields']['classy_semester_id']['field'] = 'classy_semester_id';
$handler->display->display_options['fields']['classy_semester_id']['relationship'] = 'class_id';
$handler->display->display_options['fields']['classy_semester_id']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['external'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['classy_semester_id']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['classy_semester_id']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['trim'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['alter']['html'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['element_label_colon'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['element_default_classes'] = 1;
$handler->display->display_options['fields']['classy_semester_id']['hide_empty'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['empty_zero'] = 0;
$handler->display->display_options['fields']['classy_semester_id']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['classy_semester_id']['settings'] = array(
  'link' => 0,
);
$handler->display->display_options['fields']['classy_semester_id']['field_api_classes'] = 0;
/* Field: Content: Time */
$handler->display->display_options['fields']['classy_time_id']['id'] = 'classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['table'] = 'field_data_classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['field'] = 'classy_time_id';
$handler->display->display_options['fields']['classy_time_id']['relationship'] = 'class_id';
$handler->display->display_options['fields']['classy_time_id']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['external'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['classy_time_id']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['classy_time_id']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['trim'] = 0;
$handler->display->display_options['fields']['classy_time_id']['alter']['html'] = 0;
$handler->display->display_options['fields']['classy_time_id']['element_label_colon'] = 0;
$handler->display->display_options['fields']['classy_time_id']['element_default_classes'] = 1;
$handler->display->display_options['fields']['classy_time_id']['hide_empty'] = 0;
$handler->display->display_options['fields']['classy_time_id']['empty_zero'] = 0;
$handler->display->display_options['fields']['classy_time_id']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['classy_time_id']['settings'] = array(
  'link' => 0,
);
$handler->display->display_options['fields']['classy_time_id']['field_api_classes'] = 0;
/* Filter criterion: User: Name */
$handler->display->display_options['filters']['uid']['id'] = 'uid';
$handler->display->display_options['filters']['uid']['table'] = 'users';
$handler->display->display_options['filters']['uid']['field'] = 'uid';
$handler->display->display_options['filters']['uid']['relationship'] = 'student_id';
$handler->display->display_options['filters']['uid']['value'] = '';
$handler->display->display_options['filters']['uid']['exposed'] = TRUE;
$handler->display->display_options['filters']['uid']['expose']['operator_id'] = 'uid_op';
$handler->display->display_options['filters']['uid']['expose']['label'] = 'Student';
$handler->display->display_options['filters']['uid']['expose']['operator'] = 'uid_op';
$handler->display->display_options['filters']['uid']['expose']['identifier'] = 'uid';
$handler->display->display_options['filters']['uid']['expose']['multiple'] = FALSE;
$handler->display->display_options['filters']['uid']['expose']['reduce'] = 0;

/* Display: Overview */
$handler = $view->new_display('page', 'Overview', 'overview');
$handler->display->display_options['path'] = 'admin/classy/students';
$handler->display->display_options['menu']['type'] = 'tab';
$handler->display->display_options['menu']['title'] = 'Students';
$handler->display->display_options['menu']['weight'] = '0';
$handler->display->display_options['menu']['context'] = 0;
$handler->display->display_options['tab_options']['weight'] = '0';

/* Display: Class */
$handler = $view->new_display('page', 'Class', 'classlist');
$handler->display->display_options['defaults']['title'] = FALSE;
$handler->display->display_options['title'] = 'Class Enrollment';
$handler->display->display_options['defaults']['empty'] = FALSE;
/* No results behavior: Global: Text area */
$handler->display->display_options['empty']['area']['id'] = 'area';
$handler->display->display_options['empty']['area']['table'] = 'views';
$handler->display->display_options['empty']['area']['field'] = 'area';
$handler->display->display_options['empty']['area']['empty'] = FALSE;
$handler->display->display_options['empty']['area']['content'] = 'Please return to the class list page';
$handler->display->display_options['empty']['area']['format'] = 'plain_text';
$handler->display->display_options['empty']['area']['tokenize'] = 0;
$handler->display->display_options['defaults']['fields'] = FALSE;
/* Field: User: Name */
$handler->display->display_options['fields']['name']['id'] = 'name';
$handler->display->display_options['fields']['name']['table'] = 'users';
$handler->display->display_options['fields']['name']['field'] = 'name';
$handler->display->display_options['fields']['name']['relationship'] = 'student_id';
$handler->display->display_options['fields']['name']['label'] = 'Student';
$handler->display->display_options['fields']['name']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['name']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['name']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['name']['alter']['external'] = 0;
$handler->display->display_options['fields']['name']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['name']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['name']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['name']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['name']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['name']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['name']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['name']['alter']['trim'] = 0;
$handler->display->display_options['fields']['name']['alter']['html'] = 0;
$handler->display->display_options['fields']['name']['element_label_colon'] = 0;
$handler->display->display_options['fields']['name']['element_default_classes'] = 1;
$handler->display->display_options['fields']['name']['hide_empty'] = 0;
$handler->display->display_options['fields']['name']['empty_zero'] = 0;
$handler->display->display_options['fields']['name']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['name']['link_to_user'] = 1;
$handler->display->display_options['fields']['name']['overwrite_anonymous'] = 0;
$handler->display->display_options['fields']['name']['format_username'] = 1;
/* Field: User: E-mail */
$handler->display->display_options['fields']['mail']['id'] = 'mail';
$handler->display->display_options['fields']['mail']['table'] = 'users';
$handler->display->display_options['fields']['mail']['field'] = 'mail';
$handler->display->display_options['fields']['mail']['relationship'] = 'student_id';
$handler->display->display_options['fields']['mail']['label'] = 'Email';
$handler->display->display_options['fields']['mail']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['mail']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['mail']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['mail']['alter']['external'] = 0;
$handler->display->display_options['fields']['mail']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['mail']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['mail']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['mail']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['mail']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['mail']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['mail']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['mail']['alter']['trim'] = 0;
$handler->display->display_options['fields']['mail']['alter']['html'] = 0;
$handler->display->display_options['fields']['mail']['element_label_colon'] = 0;
$handler->display->display_options['fields']['mail']['element_default_classes'] = 1;
$handler->display->display_options['fields']['mail']['hide_empty'] = 0;
$handler->display->display_options['fields']['mail']['empty_zero'] = 0;
$handler->display->display_options['fields']['mail']['hide_alter_empty'] = 1;
/* Field: Content: Title */
$handler->display->display_options['fields']['title']['id'] = 'title';
$handler->display->display_options['fields']['title']['table'] = 'node';
$handler->display->display_options['fields']['title']['field'] = 'title';
$handler->display->display_options['fields']['title']['relationship'] = 'classy_course_id_target_id';
$handler->display->display_options['fields']['title']['label'] = 'Course';
$handler->display->display_options['fields']['title']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['title']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['title']['alter']['external'] = 0;
$handler->display->display_options['fields']['title']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['title']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['title']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['title']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['title']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['title']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['title']['alter']['trim'] = 0;
$handler->display->display_options['fields']['title']['alter']['html'] = 0;
$handler->display->display_options['fields']['title']['element_label_colon'] = 0;
$handler->display->display_options['fields']['title']['element_default_classes'] = 1;
$handler->display->display_options['fields']['title']['hide_empty'] = 0;
$handler->display->display_options['fields']['title']['empty_zero'] = 0;
$handler->display->display_options['fields']['title']['hide_alter_empty'] = 1;
$handler->display->display_options['fields']['title']['link_to_node'] = 0;
/* Field: Classy: Grade */
$handler->display->display_options['fields']['grade']['id'] = 'grade';
$handler->display->display_options['fields']['grade']['table'] = 'classy_grades';
$handler->display->display_options['fields']['grade']['field'] = 'grade';
$handler->display->display_options['fields']['grade']['alter']['alter_text'] = 0;
$handler->display->display_options['fields']['grade']['alter']['make_link'] = 0;
$handler->display->display_options['fields']['grade']['alter']['absolute'] = 0;
$handler->display->display_options['fields']['grade']['alter']['external'] = 0;
$handler->display->display_options['fields']['grade']['alter']['replace_spaces'] = 0;
$handler->display->display_options['fields']['grade']['alter']['trim_whitespace'] = 0;
$handler->display->display_options['fields']['grade']['alter']['nl2br'] = 0;
$handler->display->display_options['fields']['grade']['alter']['word_boundary'] = 1;
$handler->display->display_options['fields']['grade']['alter']['ellipsis'] = 1;
$handler->display->display_options['fields']['grade']['alter']['more_link'] = 0;
$handler->display->display_options['fields']['grade']['alter']['strip_tags'] = 0;
$handler->display->display_options['fields']['grade']['alter']['trim'] = 0;
$handler->display->display_options['fields']['grade']['alter']['html'] = 0;
$handler->display->display_options['fields']['grade']['element_label_colon'] = 0;
$handler->display->display_options['fields']['grade']['element_default_classes'] = 1;
$handler->display->display_options['fields']['grade']['hide_empty'] = 0;
$handler->display->display_options['fields']['grade']['empty_zero'] = 0;
$handler->display->display_options['fields']['grade']['hide_alter_empty'] = 1;
$handler->display->display_options['defaults']['arguments'] = FALSE;
/* Contextual filter: Content: Nid */
$handler->display->display_options['arguments']['nid']['id'] = 'nid';
$handler->display->display_options['arguments']['nid']['table'] = 'node';
$handler->display->display_options['arguments']['nid']['field'] = 'nid';
$handler->display->display_options['arguments']['nid']['relationship'] = 'class_id';
$handler->display->display_options['arguments']['nid']['default_action'] = 'empty';
$handler->display->display_options['arguments']['nid']['default_argument_type'] = 'fixed';
$handler->display->display_options['arguments']['nid']['default_argument_skip_url'] = 0;
$handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
$handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
$handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
$handler->display->display_options['arguments']['nid']['specify_validation'] = 1;
$handler->display->display_options['arguments']['nid']['validate']['type'] = 'node';
$handler->display->display_options['arguments']['nid']['validate_options']['types'] = array(
  'class' => 'class',
);
$handler->display->display_options['arguments']['nid']['validate_options']['access'] = 0;
$handler->display->display_options['arguments']['nid']['break_phrase'] = 0;
$handler->display->display_options['arguments']['nid']['not'] = 0;
$handler->display->display_options['defaults']['filters'] = FALSE;
$handler->display->display_options['path'] = 'admin/classy/class/%';